# Generated by Django 4.0.5 on 2022-07-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZAR_LIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('briefly', models.CharField(max_length=250, verbose_name='Краткая информация')),
                ('book', models.TextField(verbose_name='Книга')),
                ('data', models.DateTimeField(verbose_name='Дата добавления')),
            ],
        ),
    ]
