# Generated by Django 4.0.5 on 2022-07-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zar_lit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zar_lit',
            options={'verbose_name': 'Зарубежная литература', 'verbose_name_plural': 'Зарубежная литература'},
        ),
        migrations.AddField(
            model_name='zar_lit',
            name='author',
            field=models.CharField(default='name', max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='zar_lit',
            name='book',
            field=models.FileField(upload_to='', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='zar_lit',
            name='briefly',
            field=models.TextField(verbose_name='Краткая информация'),
        ),
    ]
