# Generated by Django 4.0.5 on 2022-07-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zar_lit', '0002_alter_zar_lit_options_zar_lit_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zar_lit',
            name='image',
            field=models.FileField(default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='zar_lit',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='Автор'),
        ),
    ]
