# Generated by Django 4.0.5 on 2022-07-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zar_lit', '0003_zar_lit_image_alter_zar_lit_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zar_lit',
            name='image',
            field=models.FileField(upload_to='img/'),
        ),
    ]
