# Generated by Django 4.0.5 on 2022-07-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fantasy',
            options={'verbose_name': 'Фэнтази', 'verbose_name_plural': 'Фэнтази'},
        ),
    ]
